[package]
name = "rutie-serde"
version = "0.1.0"
authors = ["Logistics Team <logistics-team@deliveroo.co.uk>"]
edition = "2018"

[dependencies]
rutie = "0.5.2"
serde = "1.0"
serde_json = "1.0"
log = "*"
